#ifndef SERVIDOR_CONSTANTESGENERALES_H
#define SERVIDOR_CONSTANTESGENERALES_H

/// GENERALES ///
static const double EPSILON_DOUBLE= 0.005;
static constexpr int ESCALA_FONDO = 1;


#endif //SERVIDOR_CONSTANTESGENERALES_H
